const products = [
    { 
        id: 1, 
        name: "Laptop", 
        category: "Electronics", 
        price: 1200, 
        quantity: 10 
    },
    { id: 2, 
        name: "Smartphone", 
        category: "Electronics", 
        price: 800, 
        quantity: 12 
    },
    { id: 3, 
        name: "Headphones", 
        category: "Accessories", 
        price: 150, 
        quantity: 15 },
    { id: 4, 
        name: "Gaming Console", 
        category: "Electronics", 
        price: 500, 
        quantity: 19 },
    { id: 5, 
        name: "Running Shoes", 
        category: "Footwear", 
        price: 100, 
        quantity: 20 },
    { id: 6, 
        name: "Backpack", 
        category: "Bags", 
        price: 60, 
        quantity: 9 },
    { id: 7, 
        name: "Wristwatch", 
        category: "Accessories", 
        price: 250, 
        quantity: 10 },
    { id: 8, 
        name: "Sunglasses", 
        category: "Accessories", 
        price: 75, 
        quantity: 17 },
    { id: 9, 
        name: "Notebook", 
        category: "Stationery", 
        price: 5, 
        quantity: 22 },
    { id: 10, 
        name: "Water Bottle", 
        category: "Lifestyle", 
        price: 25, 
        quantity: 10 },

  ]